SET SERVEROUTPUT ON
--programa para classificar o cliente
DECLARE
   v_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type := 120000;
   v_CATEGORIA CLIENTE.CATEGORIA%type;
BEGIN
   IF v_FATURAMENTO <= 10000 THEN
      v_CATEGORIA := 'PEQUENO';
   ELSIF v_FATURAMENTO <= 50000 THEN
      v_CATEGORIA := 'MÉDIO';
   ELSIF v_FATURAMENTO <= 100000 THEN
      v_CATEGORIA := 'MÉDIO GRANDE';
   ELSE
      v_CATEGORIA := 'GRANDE';
   END IF;
   dbms_output.put_line('A Categoria é ' || v_CATEGORIA);
END;


--vreação da funçao 
CREATE OR REPLACE FUNCTION categoria_cliente
(p_FATURAMENTO IN CLIENTE.FATURAMENTO_PREVISTO%type)
RETURN CLIENTE.CATEGORIA%type
IS
   v_CATEGORIA CLIENTE.CATEGORIA%type;
BEGIN
   IF p_FATURAMENTO <= 10000 THEN
      v_CATEGORIA := 'PEQUENO';
   ELSIF p_FATURAMENTO <= 50000 THEN
      v_CATEGORIA := 'MÉDIO';
   ELSIF p_FATURAMENTO <= 100000 THEN
      v_CATEGORIA := 'MÉDIO GRANDE';
   ELSE
      v_CATEGORIA := 'GRANDE';
   END IF;
   RETURN v_CATEGORIA;
END;

--declarando as variaveis e executando a função
VARIABLE g_CATEGORIA VARCHAR2(100);
EXECUTE :g_CATEGORIA:=categoria_cliente(120000);
PRINT g_CATEGORIA;

--nova procedure
CREATE OR REPLACE PROCEDURE incluir_cliente
(
p_ID CLIENTE.ID%type,
p_RAZAO CLIENTE.RAZAO_SOCIAL%type,
p_CNPJ CLIENTE.CNPJ%type,
p_SEGMERCADO CLIENTE.SEGMERCADO_ID%type,
p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type
)
IS
v_CATEGORIA CLIENTE.CATEGORIA%type;
BEGIN

   v_CATEGORIA := categoria_cliente(p_FATURAMENTO);

   INSERT INTO CLIENTE
   VALUES 
   (p_ID, p_RAZAO, p_CNPJ, p_SEGMERCADO, SYSDATE, p_FATURAMENTO, v_CATEGORIA);
   COMMIT;
END;

--Executando a procedure
EXECUTE incluir_cliente(2, 'SUPERMERCADO DO VALE','11111111111',1,90000);
EXECUTE incluir_cliente(3, 'SUPERMERCADO CARIOCA','22222222222',1,30000);